const books = [
  {
    id: 1,
    title: "The Lost Expedition",
    author: "Tom Hardy",
    price: 18.25,
    image: "/images/a9f22682695088d2cd5ee6ba17620b9a47ce227c.jpg",
    description: "An adventurer’s perilous quest in the Amazon jungle.",
    stars: 1,
  },
  {
    id: 2,
    title: "Taste of Italy",
    author: "Gina Rossi",
    price: 15.75,
    image: "/images/brown_book.png",
    description:
      "Authentic Italian recipes to bring the flavors of Italy home.",
    stars: 2,
  },
  {
    id: 3,
    title: "Learning React",
    author: "Alex Johnson",
    price: 29.99,
    image: "/images/blue_book.jpg",
    description:
      "A comprehensive guide to mastering React.js and modern web development.",
    stars: 3,
  },
  {
    id: 4,
    title: "The Silent Forest",
    author: "David Kim",
    price: 12.99,
    image: "/images/yellow_book.jpg",
    description: "A chilling suspense story set in a haunted woodland.",
    stars: 4,
  },
  {
    id: 5,
    title: "Pacani",
    author: "Nikita Shkatula",
    price: 10.99,
    image: "/images/Cooking Made Easy.svg",
    description: "Lutie.",
    stars: 5,
  },
  {
    id: 6,
    title: "Mama",
    author: "Kirill Belko",
    price: 2.99,
    image: "/images/Pacani.jpg",
    description: "I love Tanya.",
    stars: 5,
  },
  {
    id: 7,
    title: "Papa",
    author: "Stanislav Horba",
    price: 4.99,
    image: "/images/Mystery of the Lost Island.svg",
    description: "I love mamochka.",
    stars: 5,
  },
];
